//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Default_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Boolean Teleport;
        
        public Valve.VR.SteamVR_Action_Skeleton SkeletonLeft;
        
        public Valve.VR.SteamVR_Action_Skeleton SkeletonRight;
        
        public Valve.VR.SteamVR_Action_Pose Pose;
        
        public Valve.VR.SteamVR_Action_Boolean MagicWindow;
    }
}
